// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeyName() {
  return window['go']['handlers']['KeyPathSelect']['GetKeyName']();
}

export function SetKey(arg1, arg2) {
  return window['go']['handlers']['KeyPathSelect']['SetKey'](arg1, arg2);
}
