// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeyName():Promise<string>;

export function SetKey(arg1:string,arg2:string):Promise<void>;
