// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {services} from '../models';

export function GetLogLevel():Promise<number>;

export function GetLogs(arg1:number):Promise<handlers.LogsOperationResult>;

export function GetShowByType():Promise<services.LogsToShow>;

export function MarkAllAsRead():Promise<handlers.OperationResult>;

export function MarkAsRead(arg1:number):Promise<handlers.OperationResult>;

export function SetLogLevel(arg1:services.LogLevel):Promise<handlers.OperationResult>;

export function SetShowByType(arg1:services.LogsToShow):Promise<handlers.OperationResult>;
