// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogLevel() {
  return window['go']['handlers']['Logs']['GetLogLevel']();
}

export function GetLogs(arg1) {
  return window['go']['handlers']['Logs']['GetLogs'](arg1);
}

export function GetShowByType() {
  return window['go']['handlers']['Logs']['GetShowByType']();
}

export function MarkAllAsRead() {
  return window['go']['handlers']['Logs']['MarkAllAsRead']();
}

export function MarkAsRead(arg1) {
  return window['go']['handlers']['Logs']['MarkAsRead'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['handlers']['Logs']['SetLogLevel'](arg1);
}

export function SetShowByType(arg1) {
  return window['go']['handlers']['Logs']['SetShowByType'](arg1);
}
