// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetErrorAndMessageCount() {
  return window['go']['handlers']['LogsUtils']['GetErrorAndMessageCount']();
}
