// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLog(arg1) {
  return window['go']['handlers']['LogView']['GetLog'](arg1);
}
