// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function IsCurrentlyLoading():Promise<boolean>;

export function SyncLogs():Promise<handlers.OperationResult>;
