// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsCurrentlyLoading() {
  return window['go']['handlers']['SyncLogs']['IsCurrentlyLoading']();
}

export function SyncLogs() {
  return window['go']['handlers']['SyncLogs']['SyncLogs']();
}
